//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.LoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginReference.LoginWebServiceSoap")]
    public interface LoginWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebRole1.LoginReference.HelloWorldResponse HelloWorld(WebRole1.LoginReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRole1.LoginReference.HelloWorldResponse> HelloWorldAsync(WebRole1.LoginReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebRole1.LoginReference.LoginResponse Login(WebRole1.LoginReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRole1.LoginReference.LoginResponse> LoginAsync(WebRole1.LoginReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name substring from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        WebRole1.LoginReference.GetMoviesResponse GetMovies(WebRole1.LoginReference.GetMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRole1.LoginReference.GetMoviesResponse> GetMoviesAsync(WebRole1.LoginReference.GetMoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebRole1.LoginReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebRole1.LoginReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebRole1.LoginReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebRole1.LoginReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovies", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.GetMoviesRequestBody Body;
        
        public GetMoviesRequest() {
        }
        
        public GetMoviesRequest(WebRole1.LoginReference.GetMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string substring;
        
        public GetMoviesRequestBody() {
        }
        
        public GetMoviesRequestBody(string substring) {
            this.substring = substring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRole1.LoginReference.GetMoviesResponseBody Body;
        
        public GetMoviesResponse() {
        }
        
        public GetMoviesResponse(WebRole1.LoginReference.GetMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMoviesResult;
        
        public GetMoviesResponseBody() {
        }
        
        public GetMoviesResponseBody(string GetMoviesResult) {
            this.GetMoviesResult = GetMoviesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWebServiceSoapChannel : WebRole1.LoginReference.LoginWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWebServiceSoapClient : System.ServiceModel.ClientBase<WebRole1.LoginReference.LoginWebServiceSoap>, WebRole1.LoginReference.LoginWebServiceSoap {
        
        public LoginWebServiceSoapClient() {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRole1.LoginReference.HelloWorldResponse WebRole1.LoginReference.LoginWebServiceSoap.HelloWorld(WebRole1.LoginReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebRole1.LoginReference.HelloWorldRequest inValue = new WebRole1.LoginReference.HelloWorldRequest();
            inValue.Body = new WebRole1.LoginReference.HelloWorldRequestBody();
            WebRole1.LoginReference.HelloWorldResponse retVal = ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRole1.LoginReference.HelloWorldResponse> WebRole1.LoginReference.LoginWebServiceSoap.HelloWorldAsync(WebRole1.LoginReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRole1.LoginReference.HelloWorldResponse> HelloWorldAsync() {
            WebRole1.LoginReference.HelloWorldRequest inValue = new WebRole1.LoginReference.HelloWorldRequest();
            inValue.Body = new WebRole1.LoginReference.HelloWorldRequestBody();
            return ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRole1.LoginReference.LoginResponse WebRole1.LoginReference.LoginWebServiceSoap.Login(WebRole1.LoginReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            WebRole1.LoginReference.LoginRequest inValue = new WebRole1.LoginReference.LoginRequest();
            inValue.Body = new WebRole1.LoginReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebRole1.LoginReference.LoginResponse retVal = ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRole1.LoginReference.LoginResponse> WebRole1.LoginReference.LoginWebServiceSoap.LoginAsync(WebRole1.LoginReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRole1.LoginReference.LoginResponse> LoginAsync(string username, string password) {
            WebRole1.LoginReference.LoginRequest inValue = new WebRole1.LoginReference.LoginRequest();
            inValue.Body = new WebRole1.LoginReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRole1.LoginReference.GetMoviesResponse WebRole1.LoginReference.LoginWebServiceSoap.GetMovies(WebRole1.LoginReference.GetMoviesRequest request) {
            return base.Channel.GetMovies(request);
        }
        
        public string GetMovies(string substring) {
            WebRole1.LoginReference.GetMoviesRequest inValue = new WebRole1.LoginReference.GetMoviesRequest();
            inValue.Body = new WebRole1.LoginReference.GetMoviesRequestBody();
            inValue.Body.substring = substring;
            WebRole1.LoginReference.GetMoviesResponse retVal = ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).GetMovies(inValue);
            return retVal.Body.GetMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRole1.LoginReference.GetMoviesResponse> WebRole1.LoginReference.LoginWebServiceSoap.GetMoviesAsync(WebRole1.LoginReference.GetMoviesRequest request) {
            return base.Channel.GetMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRole1.LoginReference.GetMoviesResponse> GetMoviesAsync(string substring) {
            WebRole1.LoginReference.GetMoviesRequest inValue = new WebRole1.LoginReference.GetMoviesRequest();
            inValue.Body = new WebRole1.LoginReference.GetMoviesRequestBody();
            inValue.Body.substring = substring;
            return ((WebRole1.LoginReference.LoginWebServiceSoap)(this)).GetMoviesAsync(inValue);
        }
    }
}
